# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "cc-christmas-app"
client_id = "6b2bfa27988602ff1c8ecc69d06f6087"
application_url = "https://deficit-approve-dee-mean.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://deficit-approve-dee-mean.trycloudflare.com/auth/callback",
  "https://deficit-approve-dee-mean.trycloudflare.com/auth/shopify/callback",
  "https://deficit-approve-dee-mean.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cc-app-store.myshopify.com"
