# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "christmas"
client_id = "c43afed08692a411789ae9c107c191f8"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
